// Generated by gencpp from file ros_counteruav/wav.msg
// DO NOT EDIT!


#ifndef ROS_COUNTERUAV_MESSAGE_WAV_H
#define ROS_COUNTERUAV_MESSAGE_WAV_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_counteruav
{
template <class ContainerAllocator>
struct wav_
{
  typedef wav_<ContainerAllocator> Type;

  wav_()
    : wavdata()
    , time(0)  {
    }
  wav_(const ContainerAllocator& _alloc)
    : wavdata(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wavdata_type;
  _wavdata_type wavdata;

   typedef int32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::ros_counteruav::wav_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_counteruav::wav_<ContainerAllocator> const> ConstPtr;

}; // struct wav_

typedef ::ros_counteruav::wav_<std::allocator<void> > wav;

typedef boost::shared_ptr< ::ros_counteruav::wav > wavPtr;
typedef boost::shared_ptr< ::ros_counteruav::wav const> wavConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_counteruav::wav_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_counteruav::wav_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_counteruav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'ros_counteruav': ['/home/project/counterUAV/ROS_system/catkin_ws/src/ros_counteruav/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ros_counteruav::wav_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_counteruav::wav_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_counteruav::wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_counteruav::wav_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_counteruav::wav_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_counteruav::wav_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_counteruav::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c745b9bbbbcdca306399d485d1fa8c2";
  }

  static const char* value(const ::ros_counteruav::wav_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c745b9bbbbcdca3ULL;
  static const uint64_t static_value2 = 0x06399d485d1fa8c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_counteruav::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_counteruav/wav";
  }

  static const char* value(const ::ros_counteruav::wav_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_counteruav::wav_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] wavdata\n"
"int32 time\n"
;
  }

  static const char* value(const ::ros_counteruav::wav_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_counteruav::wav_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wavdata);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wav_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_counteruav::wav_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_counteruav::wav_<ContainerAllocator>& v)
  {
    s << indent << "wavdata[]" << std::endl;
    for (size_t i = 0; i < v.wavdata.size(); ++i)
    {
      s << indent << "  wavdata[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.wavdata[i]);
    }
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_COUNTERUAV_MESSAGE_WAV_H
